name: flutter_project_labour_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_slidable: ^3.0.0
  get: ^4.6.5
  http: ^1.1.0
  modal_bottom_sheet: ^2.1.2
  pinput: ^2.2.31
  syncfusion_flutter_core: ^22.1.39
  syncfusion_flutter_sliders: ^22.1.39

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Branding SF
      fonts:
        - asset: assets/fonts/BrandingSF-Bold.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
    - family: Sansita
      fonts:
        - asset: assets/fonts/Sansita-Regular.ttf
