name: flutter_project_labour_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bubble: ^1.2.1
  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^3.0.0
  fluttertoast: ^8.2.2
  focused_menu: ^1.0.5
  get: ^4.6.5
  http: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  lottie: ^2.6.0
  modal_bottom_sheet: ^2.1.2
  modal_progress_hud_nsn: ^0.4.0
  pinput: ^2.2.31
  syncfusion_flutter_core: ^22.1.39
  syncfusion_flutter_sliders: ^22.1.39
  toggle_switch: ^2.1.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Branding SF
      fonts:
        - asset: assets/fonts/BrandingSF-Bold.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
    - family: Sansita
      fonts:
        - asset: assets/fonts/Sansita-Regular.ttf
