import 'package:flutter/material.dart';

const Color subtitleGrey = Color(0x991A1A1A);
const Color primaryRed = Color(0xFFFF4E34);
const Color lightGrey = Color(0xFFCCCCCC);
const Color bottomGrey = Color(0xFF747474);
const Color otpColor = Color(0xFF3E3E3E);
const Color otpBoxColor = Color(0xFFEFEFEF);
const Color inactiveTrackColor = Color(0xFFEBEBEB);
const Color allSetPageBackground = Color(0xFF78C4E4);
const Color allSetPageTextColor = Color(0xFFB6B6B6);
const Color searchBarColor = Color(0xFFF1F1F1);
const Color searchBarIconColor = Color(0xFFA1A1A1);
const Color cardSubtitle = Color(0xFFA3A3A3);
const Color lightBlue = Color(0xFFE7FAFC);
const Color timeGrey = Color(0xFFBFBFBF);
const Color chatTick = Color(0xFF7EB2EE);
const Color contactInfo = Color(0xFF3D74D8);
const Color aboutGrey = Color(0xFF6A6A6A);
const Color darkRed = Color(0xFFEF0F33);
const Color emptyPageTitleColor = Color(0xFF4A4A4A);
const Color jobDescTileTextGrey = Color(0xFF2B2B2B);
const Color bulletThumb = Color(0xFFD9D9D9);
const Color ratingYellow = Color(0xFFFCFF52);
const Color authIconColor = Color(0xFF898989);